
// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design",        "CA1028:Enum Storage should be Int32")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design",        "CA1031:Do not catch general exception types")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design",        "CA1032:Implement standard exception constructors")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design",        "CA1033:Interface methods should be callable by child types")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design",        "CA1034:Nested types should not be visible")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design",        "CA1051:Do not declare visible instance fields")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design",        "CA1060:Move pinvokes to native methods class")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design",        "CA1062:Validate arguments of public methods")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design",        "CA1065:Do not raise exceptions in unexpected locations")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design",        "CA1707:Remove the underscores from member name")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design",        "CA1710:Identifiers should have correct suffix")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design",        "CA1724:Type names should not match namespaces.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design",        "CA1819:Properties should not return arrays")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1308:Normalize strings to uppercase")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming",        "CA1716:Identifiers should not match keywords")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming",        "CA1720:Identifier contains type name")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance",   "CA1812: Avoid uninstantiated internal classes")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Security",      "CA2100:Review SQL queries for security vulnerabilities")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style",         "IDE0016:Use 'throw' expression")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style",         "IDE0028:Simplify collection initialization")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style",         "IDE0029:Use coalesce expression") ]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style",         "IDE0044:Add readonly modifier")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style",         "IDE0059:Unnecessary assignment of a value")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style",         "IDE0060:Remove unused parameter")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style",         "IDE1006:Naming Styles") ]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage",         "CA1714:Flags enums should have plural names")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage",         "CA1801:Review unused parameters.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage",         "CA2237:Mark ISerializable types with serializable")]
