using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Design",        "CA1031:Do not catch general exception types")]
[assembly: SuppressMessage("Design",        "CA1051:Do not declare visible instance fields")]
[assembly: SuppressMessage("Design",        "CA1062:Validate arguments of public methods")]
[assembly: SuppressMessage("Design",        "CA1068:Should take CancellationToken as the last parameter")]
[assembly: SuppressMessage("Design",        "CA1707:Remove the underscores from member name")]
[assembly: SuppressMessage("Design",        "CA1710:Identifiers should have correct suffix")]
[assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters")]
[assembly: SuppressMessage("Naming",        "CA1720:Identifier contains type name")]
[assembly: SuppressMessage("Naming",        "CA1721:Property names should not match get methods")]
[assembly: SuppressMessage("Performance",   "CA1812: Avoid uninstantiated internal classes", Justification = "Visual studio ....")]
[assembly: SuppressMessage("Reliability",   "CA2007:Do not directly await a Task")]
[assembly: SuppressMessage("Style",         "IDE0016:Use 'throw' expression")]
[assembly: SuppressMessage("Style",         "IDE0044:Add readonly modifier")]
[assembly: SuppressMessage("Style",         "IDE0059:Unnecessary assignment of a value")]
[assembly: SuppressMessage("Style",         "IDE0060:Remove unused parameter")]
[assembly: SuppressMessage("Style",         "IDE1006:Naming Styles")]
[assembly: SuppressMessage("Usage",         "CA1714:Flags enums should have plural names")]
[assembly: SuppressMessage("Usage",         "CA1801:Review unused parameters.")]

[assembly: SuppressMessage("Code Quality",  "IDE0069:Disposable fields should be disposed", Scope = "member", Target = "~F:Jannesen.VisualStudioExtension.TypedTSql.LanguageService.Project._errorList")]
[assembly: SuppressMessage("Usage",         "CA2213:Disposable fields should be disposed",  Scope = "member", Target = "~F:Jannesen.VisualStudioExtension.TypedTSql.LanguageService.Project._errorList")]
[assembly: SuppressMessage("Code Quality",  "IDE0069:Disposable fields should be disposed", Scope = "member", Target = "~F:Jannesen.VisualStudioExtension.TypedTSql.LanguageService.Project._hierarchyListener")]
[assembly: SuppressMessage("Usage",         "CA2213:Disposable fields should be disposed",  Scope = "member", Target = "~F:Jannesen.VisualStudioExtension.TypedTSql.LanguageService.Project._hierarchyListener")]

[assembly: SuppressMessage("Usage",         "VSTHRD010:")]
[assembly: SuppressMessage("Usage",         "VSTHRD100:")]
[assembly: SuppressMessage("Usage",         "VSTHRD110:")]
[assembly: SuppressMessage("Usage",         "VSTHRD200:")]

[assembly: SuppressMessage("Usage",         "VSTHRD001:Avoid legacy thread switching APIs", Scope = "member", Target = "~M:Jannesen.VisualStudioExtension.TypedTSql.VSPackage.InsertTextInActiveDocument(System.String,System.Boolean)~System.Boolean")]